name: Frontend CI/CD

on:
  push:
    branches:
      - main  # Trigger only on push to main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from your GitHub repo
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install project dependencies
      - name: Install Dependencies
        run: npm ci  # Faster and cleaner than npm install

      # Step 4: Optional - Run linter (skip errors to not fail build)
      - name: Run Linter
        run: npm run lint || true

      # Step 5: Optional - Run tests (skip errors to continue)
      - name: Run Tests
        run: npm test || true

      # Step 6: Build your frontend project (React/Vue/etc.)
      - name: Build Frontend
        run: npm run build

      # Step 7: Deploy to GitHub Pages (great for static frontend apps)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build  # Use ./dist for Vue or Vite
